version: '3'

services:
    #mqtt
    mosquitto:
        container_name: mqtt
        hostname: mosquitto
        restart: always
        image: eclipse-mosquitto
        privileged: true
        ports:
            - "...:..."
            - "...:..."
        volumes: 
            - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mqtt/data:/mosquitto/data
            - ./mqtt/log:/mosquitto/log
#        network_mode: "host"
        networks:
            - default

networks:
    default:
